const SAMPLE_ACTION_TYPE_1 = 'SAMPLE_ACTION_TYPE_1';
const SAMPLE_ACTION_TYPE_1_SUCCESS = 'SAMPLE_ACTION_TYPE_1_SUCCESS';
const SAMPLE_ACTION_TYPE_2 = 'SAMPLE_ACTION_TYPE_2';
const SAMPLE_ACTION_TYPE_2_SUCCESS = 'SAMPLE_ACTION_TYPE_2_SUCCESS';

module.exports = {
    SAMPLE_ACTION_TYPE_1,
    SAMPLE_ACTION_TYPE_1_SUCCESS,
    SAMPLE_ACTION_TYPE_2,
    SAMPLE_ACTION_TYPE_2_SUCCESS
}